version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/var/www/html
    ports:
      - "7100:8000"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
